repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      name: flake8 except __init__.py
      args: [--exclude=__init__.py]
    - id: flake8
      name: flake8 only __init__.py
      args: [--ignore=F401]  # ignore imported unused in __init__.py
      files: __init__.py
  - repo: local
    hooks:
      - id: pytest
        name: Check pytest unit tests pass
        entry: make test
        language: system
